export default [
    { name: 'Push-ups', reps: 'Max', weight: 'Body-weight', sets: '3', },
    { name: 'Military Push-ups', reps: 'Max', weight: 'Body-weight', sets: '3', },
    { name: 'Diamond Push-ups', reps: 'Max', weight: 'Body-weight', sets: '3', },
    { name: 'Wide-fly Push-ups', reps: 'Max', weight: 'Body-weight', sets: '3', },
    { name: 'Spider-Man Push-ups', reps: 'Max', weight: 'Body-weight', sets: '3', },
    { name: 'Chin-ups', reps: 'Max', weight: 'Body-weight', sets: '3', },
    { name: 'Pull-ups', reps: 'Max', weight: 'Body-weight', sets: '3', },
    { name: 'Supermans', reps: 'Max', weight: 'Body-weight', sets: '3', },
    { name: 'Overhead Lat-pull', reps: '10-12', weight: 'Heavy enough to fail between 10-12', sets: '3', },
    { name: 'Renegade Rows', reps: '10-12', weight: 'Heavy enough to fail between 10-12', sets: '3', },
    { name: 'Cross-body Alternating Shoulder Press', reps: '10-12', weight: 'Heavy enough to fail between 10-12', sets: '3', },
    { name: 'L-Raises', reps: '10-12', weight: 'Heavy enough to fail between 10-12', sets: '3', },
    { name: 'Biceps Curls', reps: '10-12', weight: 'Heavy enough to fail between 10-12', sets: '3', },
    { name: 'Hammer Curls', reps: '10-12', weight: 'Heavy enough to fail between 10-12', sets: '3', },
    { name: 'Bench Dips', reps: 'Max', weight: 'Body-weight', sets: '3', },
    { name: 'Triceps Press-down', reps: '10-12', weight: 'Heavy enough to fail between 10-12', sets: '3', },
    { name: 'Plank', reps: '1 min', weight: 'Body-weight', sets: '3', },
    { name: 'Side plank', reps: '1 min', weight: 'Body-weight', sets: '3', },
    { name: 'Opposite knee to elbow plank', reps: '1 min', weight: 'Body-weight', sets: '3', },
    { name: 'Same knee to elbow plank', reps: '1 min', weight: 'Body-weight', sets: '3', },
    { name: 'Twisting hip drop plank', reps: '1 min', weight: 'Body-weight', sets: '3', },
    { name: 'Squat', reps: 'Max', weight: 'Body-weight', sets: '3', },
    { name: 'Front lunge', reps: 'Max', weight: 'Body-weight', sets: '3', },
    { name: 'Side lunge', reps: 'Max', weight: 'Body-weight', sets: '3', },
    { name: 'Transverse lunge', reps: 'Max', weight: 'Body-weight', sets: '3', },
    { name: 'Alternating curtsy lunge', reps: 'Max', weight: 'Body-weight', sets: '3', }
]